meta_product_name: "Alla Breve"
meta_title: "Alla Breve | Tudo sobre Música Clássica"
meta_description: "O melhor portal brasileiro para leitura de artigos e críticas especializadas em música clássica. Conheça também as playlists e inicie no mundo da música clássica. Conteúdo e curadoria de Max Lima."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
